namespace: andreygubarev
name: prometheus
version: 1.0.1

readme: README.md

authors:
  - Andrey Gubarev <andrey@andreygubarev.com> (andreygubarev.com)

description: Ansible collection for prometheus
license_file: LICENSE

tags:
  - infrastructure
  - monitoring

dependencies: {}

repository: https://github.com/andreygubarev/ansible-prometheus
documentation: https://github.com/andreygubarev/ansible-prometheus
homepage: https://github.com/andreygubarev/ansible-prometheus
issues: https://github.com/andreygubarev/ansible-prometheus/issues

build_ignore:
  - Makefile
  - .venv
  - .git
  - .gitignore
