---
dependency:
  name: galaxy
driver:
  name: molecule-qemu
platforms:
  - name: ubuntu-20.04-amd64
    image: file:///Users/andrey/Downloads/focal-server-cloudimg-amd64.img
    image_arch: x86_64
    ssh_port: 10023
    ssh_user: ubuntu
provisioner:
  name: ansible
verifier:
  name: testinfra
