name: Upload Ansible Collection

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: python -m pip install --upgrade -r requirements.txt

    - name: Build collection
      run: ansible-galaxy collection build --force

    - name: Publish collection
      run: ansible-galaxy collection publish *.tar.gz --api-key ${{ secrets.GALAXY_API_KEY }}
      env:
        GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
